Repository cits5206Group9/SmallGoods-Competition-app, pull requests merged in 2025-09, with the labels that each got.

#25 First version of Database With pytest
  README.md
  app/config.py
  app/models.py
  app/models_bk.py
  app/routes.py
  migrations/README
  migrations/alembic.ini
  migrations/env.py
  migrations/script.py.mako
  migrations/versions/70a265a4a7d7_first_version_all_database_models_.py
  pytest.ini
  tests/conftest.py
  tests/test_integration.py
  tests/test_models.py
  tests/test_sanity.py
  tests/test_system.py
  tests/test_utils.py
Labels: database

#33 Redesigned competition model
  app/models.py
  app/routes/admin.py
  app/static/css/competition_create.css
  app/static/css/competition_edit.css
  app/static/css/competition_model.css
  app/static/js/competition-utils.js
  app/static/js/competition_create.js
  app/static/js/competition_edit.js
  app/static/js/competition_model.js
  app/templates/admin/competition_create.html
  app/templates/admin/competition_edit.html
  app/templates/admin/competition_model.html
  app/templates/admin/includes/_competition_templates.html
  migrations/versions/0a700744d681_update_version_2.py
Labels: enhancement, backend, database, status: done

#41 [Bug Fix]some conflicts in admin.py
  app/routes/admin.py
Labels: bug

#39 Referee
  app/models.py
  app/routes/admin.py
  app/static/js/referee.js
  app/templates/admin/individual_referee.html
  app/templates/admin/referee.html
  app/templates/admin/referee_dashboard.html
  app/templates/admin/referee_login.html
  app/templates/admin/referee_settings.html
  app/templates/admin/results_dashboard.html
  app/utils/__init__.py
  app/utils/referee_generator.py
  migrations/versions/add_referee_competition_link.py
Labels: enhancement, backend

#57 [Bug fixed] Syncing updates on flight_id and fetching correct entry_order in AthleteEntry table
  app/models.py
  app/routes/admin.py
  app/routes/athlete.py
  app/templates/athlete/athlete.html
Labels: bug

#59 Bug Fix Change Attemp Order won't sync with database bug
  app/models.py
  app/static/css/admin/flights_management.css
  app/static/js/admin/flights_management.js
  app/templates/admin/flights_management.html
Labels: bug
