Repository cits5206Group9/SmallGoods-Competition-app, pull requests merged in 2025-10, with the labels that each got.

#69 Moved sport type from competition to events
  app/models.py
  app/routes/admin.py
  app/routes/athlete.py
  app/static/js/competition-utils.js
  app/static/js/competition_create.js
  app/static/js/competition_edit.js
  app/templates/admin/competition_create.html
  app/templates/admin/competition_edit.html
  app/templates/admin/referee_settings.html
  app/utils/model_import.py
  create_test_competition.py
  migrations/README
  migrations/alembic.ini
  migrations/env.py
  migrations/script.py.mako
  tests/test_athlete_page.py
Labels: bug

#73 athlete & attempt selection, precise duration display in Timekeeper
  app/static/js/timekeeper.js
  app/templates/admin/timer.html
Labels: enhancement, backend

#75 [Feature] Changes for handling multiple athletes same time
  app/static/css/timekeeper.css
  app/static/js/timekeeper.js
  app/templates/admin/timer.html
Labels: enhancement, backend, frontend

#81 Added scoreboard history tool to track and edit scores
  app/routes/admin.py
  app/static/css/scoreboard_history.css
  app/static/js/scoreboard_history.js
  app/templates/admin/admin.html
  app/templates/admin/scoreboard_history.html
Labels: enhancement

#84 Display database integration & Attempt status update automation
  PR_DESCRIPTION.md
  SYNCED_TIMER_FEATURE.md
  TIMER_STATE_FIX.md
  app/__init__.py
  app/routes/admin.py
  app/routes/athlete.py
  app/routes/display.py
  app/static/js/timekeeper.js
  app/templates/display/competition.html
  create_task_def_new.py
Labels: bug, enhancement, backend, database
